server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: USUARIO-SERVICE
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/api/usuarios/**
          filters:
            - AuthFilter

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hoteles/**,/api/staffs/**

        - id: CALIFICACION-SERVICE
          uri: lb://CALIFICACION-SERVICE
          predicates:
            - Path=/api/calificaciones/**

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8880/eureka
