server:
  port: 8081 #${PORT:${SERVER_PORT:0}}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios?serverTimeZone=UTC
    username: root
    password: mysql
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-regitry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8880/eureka
